### ISSUE TITLE
Message: no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by dahlbyk** [huboard/huboard-web#295]
We have recently had several instances of:

> Message: no implicit conversion of String into Integer
>
> /app/lib/bridge/github/issues.rb:267 []=
> /app/lib/bridge/github/issues.rb:267 extended
> /app/lib/bridge/github/issues.rb:18 extend
> /app/lib/bridge/github/issues.rb:18 block in issues
> /app/vendor/bundle/ruby/2.3.0/gems/ghee-0.14.19/lib/ghee/resource_proxy.rb:51 each
> /app/vendor/bundle/ruby/2.3.0/gems/ghee-0.14.19/lib/ghee/resource_proxy.rb:51 method_missing
> /app/lib/bridge/github/issues.rb:17 issues
> /app/app/controllers/api/issues_controller.rb:11 issues

It's not immediately obvious to me what the problem might be:
https://github.com/huboard/huboard-web/blob/657abcd8e17b070775c4b3a4c8f1b05a35d1621b/lib/bridge/github/issues.rb#L266-L271

https://app.raygun.io/crashreporting/7lc2yw/errors/1334243193
https://app.raygun.io/crashreporting/7lc2yw/errors/1325060943
https://app.raygun.io/crashreporting/7lc2yw/errors/1309424285

**Comment by discorick** [comment]
Steps to reproduce:

- Log in a visit a board you are a collaborator of
- In another window hit `/logout`
- Wait 30 seconds (to trigger a board sync) and go back to the original window
- You will see:
![image](https://cloud.githubusercontent.com/assets/1130665/15190208/e134f566-176b-11e6-9946-6070720ce1f9.png)

Which is caused by:
![image](https://cloud.githubusercontent.com/assets/1130665/15190179/caf4ecca-176b-11e6-8e66-acae07c362ae.png)
